services:
  - type: web
    name: jobboard-app
    env: python
    buildCommand: ""
    startCommand: gunicorn app:app
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: jobboard_db
          property: connectionString
      - key: SECRET_KEY
        value: your-secret-key
      - key: EMAIL_USER
        value: yourappemail@gmail.com
      - key: EMAIL_PASS
        value: your_app_password
databases:
  - name: jobboard_db
